apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: c7i86fl68-dotnet-basic-gitops-repository
spec:
  url: https://github.com/testrhtaporg/c7i86fl68-dotnet-basic-gitops